### ISSUE TITLE
example.import_names.py doesn't handle clean names

### ISSUE THREAD

**Issue by Lukeluca** [cbess/inventory-checkin#7]
It looks like the script assumes there will be commas in the names, if you provide a "clean" name (without commas), it may crash.

**Comment by cbess** [comment]
Yes, the commas are for `last name, first name`. It's CSV text.

**Comment by Lukeluca** [comment]
Would adding an if block let it use the clean version?
    if parts.count() > 1:
      name = '%s %s' % (parts[1].strip().title(), parts[0].strip().title())
      continue

**Comment by cbess** [comment]
Sure, I'll update it.

**Comment by cbess** [comment]
Fixed in 25ab3d1
