### ISSUE TITLE
Guide for the repo

### ISSUE THREAD

**Issue by tOlorun** [cbess/inventory-checkin#9]
Hi Christopher,

How are you doing and how is everything with you, and your family?
Sure you are doing greatly.

Please i just came across your projects today and i was wondering if you have any guide to using them apart from the read me.

iam interested in your flask web projects

Many thanks

Cheers

Seun

**Comment by cbess** [comment]
Hi, by Jesus grace, all things are well and blessed, thanks for asking. I don't mind answering any specific questions you have, but other than whats available in the repository, no other guide is available.
